<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PaketData5GB</name>
   <tag></tag>
   <elementGuidId>f3e2b1c1-e203-40f2-94cd-4939f30c493c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ijoin-app&quot;]/div[1]/div/main/div/div/div/div[2]/div[2]/div/div/div/div/div/div[3]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
