<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PilihPengiriman</name>
   <tag></tag>
   <elementGuidId>cdfdbdec-4404-428a-bb4d-e0c0c813d5f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ijoin-app&quot;]/div[1]/div/main/div/div/div/div[1]/div/div/form/div[5]/section/div/div[1]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
