<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Buat akun Dengan_mssidn-icon</name>
   <tag></tag>
   <elementGuidId>7de6961a-3248-4b0e-a9b9-3d79887b8e84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='btn-mobile-login']/div/div)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.justify-content-center > #btn-mobile-login > div.align-self-center > div.mssidn-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mssidn-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-ciam&quot;)/div[@class=&quot;app-body&quot;]/div[1]/div[@class=&quot;auth0-login login-container&quot;]/div[@class=&quot;t-container&quot;]/div[@class=&quot;t-cols&quot;]/div[@class=&quot;t-col col-lg-7&quot;]/div[@class=&quot;login-box&quot;]/form[1]/div[@class=&quot;form-social-login&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/div[@id=&quot;btn-mobile-login&quot;]/div[@class=&quot;align-self-center&quot;]/div[@class=&quot;mssidn-icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='btn-mobile-login']/div/div)[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
